[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ollama"

[deploy]
startCommand = "ollama serve"
healthcheckPath = "/api/tags"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartMaxRetries = 10
